service: url-shortener

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless
  environment:
    SLS_STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:587678272550:table/prod-shortened-urls"
      Effect: Allow


functions:
  main:
    handler: main/index.handler
    events:
    - http:
        path: /
        method: get
  
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get

resources:
  Resources:
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: "${opt:stage, self:provider.stage}-shortened-urls"
        


package:
  exclude:
    - Resources/**
    - cli_commands
    - README.md
